<?php
/**
 * @file
 * Definition of Zurb Foundation Two column Display Suite layout.
 */

function ds_cksub_9_3stackedgrid()
{
    return array(
        'label' => t('CKSub 2 column row stacked (9-3)'),
        'regions' => array(
            'header' => t('Header'),
            'left' => t('Left'),
            'right' => t('Right'),
            'footer' => t('Footer'),
        ),
        'image' => TRUE,
    );
}
